#!/bin/sh

set -e

CONFIGDIR=/etc/console-setup

update-alternatives --install /etc/vtrgb vtrgb "$CONFIGDIR/vtrgb" 50
update-alternatives --install /etc/vtrgb vtrgb "$CONFIGDIR/vtrgb.vga" 20

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/setvtrgb" ]; then
		update-rc.d setvtrgb start 49 S . >/dev/null || exit $?
	fi
fi
# End automatically added section

