#! /bin/sh
set -e

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl "1:2.26"; then
    rm -f /etc/xdg/autostart/gnome-at-session.desktop
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/menus/gnomecc.menu 1:3.8.3-2~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/gnome-sound-applet.desktop 1:3.8.3-2~ -- "$@"
# End automatically added section

