#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
  update-alternatives --remove my.cnf /etc/mysql/my.cnf.fallback
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/mysql/my.cnf 5.6.22-1~ mysql-common -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/mysql/conf.d/.keepme 5.6.22-1~ mysql-common -- "$@"
# End automatically added section

