#!/bin/sh

set -e

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 0.9.0-2 ; then
    [ -x /usr/share/update-notifier/notify-reboot-required ] && \
        /usr/share/update-notifier/notify-reboot-required || true
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/nm-applet.conf 0.9.0-4~ network-manager-gnome -- "$@"
# End automatically added section

