#!/bin/sh -e



case "${1}" in
(configure)
    cd /dev && test -x MAKEDEV && ./MAKEDEV -v apm
    FN="/etc/modprobe.d/apm"
    if [ -f "${FN}" ] && md5sum --check --status > /dev/null 2>&1 << EOF
05bec108b10c64c5a614cf4576e5d66a  ${FN}
EOF
    then
	rm -f "${FN}"
    fi
    ;;
(abort-upgrade|abort-remove|abort-deconfigure)
    ;;
(*)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
