#! /bin/sh

set -e

case "$1" in
    configure)
    files=$(dpkg -L libpython3.5-stdlib:amd64 | sed -n '/^\/usr\/lib\/python3.5\/.*\.py$/p')
    if [ -n "$files" ]; then
	/usr/bin/python3.5 -E -S /usr/lib/python3.5/py_compile.py $files
	if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config; then
	    /usr/bin/python3.5 -E -S -O /usr/lib/python3.5/py_compile.py $files
	fi
    else
	echo >&2 "python3.5: can't get files for byte-compilation"
    fi
esac



exit 0
