#!/bin/sh -e

case "$1" in
  purge)
	rm -rf /var/lib/sudo
  ;;

  remove|upgrade|deconfigure)
  ;;

  abort-upgrade|failed-upgrade)
    if [ -e "/etc/sudoers.pre-conffile" ]; then
	mv /etc/sudoers.pre-conffile /etc/sudoers
    fi
  ;;

  *)
        echo "unknown argument --> $1" >&2
        exit 0
  ;;
esac

# remove the old init script
dpkg-maintscript-helper rm_conffile /etc/init.d/sudo 1.8.12-1ubuntu2~ sudo -- "$@"


